### PR TITLE
Add start and end times (in ticks) to MethodWeaver. This gives the us…

### PR DESCRIPTION
**Pull request by ananthonline**
…tant for performance-critical assemblies that don't want to log anything except some chosen methods/classes.

PS: Sorry about the previously closed pull requests, a bad squash screwed everything up (+_+)

### CODE REVIEW

**Comment by csnemes** [comment]
Hi,
Could you give some example use cases how start and end time would be used?  I'm just trying to understand, so that I can update the documentation. Thanks.

**Comment by ananthonline** [comment]
The start and end times can be used, for example during metrics collection. This allows us to not only find out how long a method took to execute, but also relate it to any errors that may have happened during execution (if starttime < errortime < endtime).

**Comment by csnemes** [comment]
For such purpose wouldn't be it easier to use just log4net's log date? Like the date of the trace leave entry is the endtime and date minus duration is the starttime.

**Comment by ananthonline** [comment]
No, this is unsuitable because of the following reasons.

1. There's no way to do this in a log4net config file without writing a formatter or appender in code - worse, the only way is to parse the logs in a post-process looking for matched trace pairs.
2. As I've measured this, it is inaccurate (off by as much as a couple of seconds) and therefore insufficient for high performance applications.

The fix I suggest allows both modes of usage - so existing users can continue using it as such, but others with the need for accuracy can use startTicks and endTicks.

**Comment by csnemes** [comment]
Thanks for the explanation. I just wanted to make sure that we don't reinvent something which is already there.

**Comment by csnemes** [comment]
I've merged your pull request into the dev and updated the unit tests and pulled the changes as a single PR. Thanks for your help.

**Pull request closed without merging**
